name: Quick Test

on:
  push:
    branches: [ main, develop, master ]
  pull_request:
    branches: [ main, develop, master ]

jobs:
  quick-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Playwright browsers
      run: |
        playwright install chromium
        playwright install-deps
    
    - name: Run smoke tests
      run: |
        BROWSER=chromium pytest -m "smoke" -v --alluredir=reports/allure-results
      env:
        BROWSER: chromium
        HEADLESS: true
    
    - name: Run API tests
      run: |
        pytest tests/api/ -v --alluredir=reports/allure-results
      env:
        HEADLESS: true
    
    - name: Upload Allure results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results-quick
        path: reports/allure-results/
        retention-days: 7
    
    - name: Generate and upload Allure report
      run: |
        allure generate reports/allure-results -o reports/allure-report --clean
      if: always()
    
    - name: Upload Allure report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report-quick
        path: reports/allure-report/
        retention-days: 7
      if: always()
    
    - name: Comment PR with results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const comment = `## 🚀 Quick Test Results
          
          ### Status: ${{ job.status }}
          
          ### Reports
          📋 [Download Allure Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          
          ### Next Steps
          - Review test results
          - Check Allure report for details
          - Fix any failing tests
          
          ---
          *Generated by GitHub Actions*`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
